### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by leitao** [pmem/ndctl#74] opened 2018-11-01 13:07 UTC
When compiling this package in Debian I see:

``` # make
  GEN      version.m4
make --no-print-directory all-recursive
  GEN      version.m4
Making all in .
  GEN      version.m4
  CC       util/filter.o
util/filter.c: In function ‘util_dimm_filter_by_numa_node’:
util/filter.c:299:8: warning: implicit declaration of function ‘ndctl_region_get_numa_node’; did you mean ‘ndctl_region_get_type_name’? [-Wimplicit-function-declaration]
        ndctl_region_get_numa_node(region) == numa_node)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
        ndctl_region_get_type_name
util/filter.c:299:8: warning: nested extern declaration of ‘ndctl_region_get_numa_node’ [-Wnested-externs]
util/filter.c: In function ‘mode_to_type’:
util/filter.c:359:9: error: ‘NDCTL_NS_MODE_UNKNOWN’ undeclared (first use in this function); did you mean ‘NDCTL_NS_MODE_RAW’?
  return NDCTL_NS_MODE_UNKNOWN;
         ^~~~~~~~~~~~~~~~~~~~~
         NDCTL_NS_MODE_RAW
util/filter.c:359:9: note: each undeclared identifier is reported only once for each function it appears in
util/filter.c: In function ‘util_filter_walk’:
util/filter.c:384:35: error: ‘NDCTL_NS_MODE_UNKNOWN’ undeclared (first use in this function); did you mean ‘NDCTL_NS_MODE_RAW’?
  if (mode_to_type(param->mode) == NDCTL_NS_MODE_UNKNOWN) {
                                   ^~~~~~~~~~~~~~~~~~~~~
                                   NDCTL_NS_MODE_RAW
util/filter.c: In function ‘mode_to_type’:
util/filter.c:360:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [Makefile:666: util/filter.o] Error 1
make[1]: *** [Makefile:750: all-recursive] Error 1
make: *** [Makefile:531: all] Error 2
```

**Comment by kilobyte** [comment] 2018-11-02 09:07
I can't reproduce.  However, I do see a possible problem: that function and the enum value come from ndctl.h, which is #included as ``<ndctl/ndctl.h>`` rather than ``"SOMEPATH/ndctl.h"`` (note ``<`` vs ``"``).  If you still have packages of v59 installed system-wide, their headers can be used instead of those from the source tree.

Could you check if amending that fixes the problem?  If so, then that's a bug in ndctl that should be fixed here.

**Comment by kilobyte** [comment] 2018-11-02 11:05
Hmm no, despite destroying system headers:
```
echo "#error Don't use system headers" >/usr/include/ndctl/ndctl.h
echo "#error Don't use system headers" >/usr/include/ndctl/libndctl.h
echo "#error Don't use system headers" >/usr/include/ndctl/libdaxctl.h
```
ndctl builds for me successfully.  But then, the in-tree libndctl.h has these identifiers, and it has gained them between v59 and v60 (your last attempt was on v59), so I don't see a different explanation.  Thus, care to try with either ``<`` changed to ``"`` or with system-installed headers removed?

**Comment by djbw** [comment] 2018-11-03 19:20
v63 builds ok for me on a vanilla Debian 9.5 install. It seems there's a stale libndctl.h that is being picked up.

**Comment by kilobyte** [comment] 2018-11-06 09:51
@leitao: could you please confirm if it's indeed the matter of old headers being installed?

Or if you still have problems, could you show us your packages?  It'd be interesting to test them and/or compare with what Andreas Hasenack uploaded to Ubuntu.  Duplicating work wastes some effort, but at least you can copy parts if that'd help.

(What I care about is that ndctl gets into Debian quickly, to allow time for pmdk — who does the work is less important as long as it's done :) .)

**Comment by leitao** [comment] 2018-11-06 16:24
Yes, it seems the build system was using the system ndctl header, which causes the problem.

**Comment by djbw** [comment] 2018-11-06 23:41
There's a configure option that defaults to using the local header. I would only expect it to pick up the system header if "--disable-local" was specified to the configure script. If that's not the case then it might be a bug with that option.

**Comment by leitao** [comment] 2018-11-07 12:54
I do not think used "--disabled-local" at all. I just call autogen.sh && configure && make. Anyway. this is solved now and version 63 is at Debian new queue:

https://ftp-master.debian.org/new/ndctl_63-1.html

Thanks

**Closed** 2018-11-07 12:54 UTC
