### ISSUE TITLE
"ndctl destroy-namespace -f all" Failed

### ISSUE THREAD

**Issue by chunglam1999** [pmem/ndctl#75] opened 2018-11-06 23:23 UTC
pkg version: ndctl-v63
Issue: "ndctl destroy-namespace -f all" failed but the namespace were actually destroyed. Only happened on AppDirectNonInterleaved type namespaces.

 [root]# ipmctl show -region 
SocketID             ISetID    PersistentMemoryType  Capacity FreeCapacity  HealthState 
       0 0xedfbda90d31b8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy 
       0 0x63f1da90121a8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy 
       0 0x0a05da90891c8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy 
       0 0xb3fbda901a1b8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy 
       1 0x0ffbda90f01b8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy 
       1 0x73fbda90fa1b8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy 
       1 0xea05da90b91c8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy 
       1 0x3df1da905b1a8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy 

[root]# ndctl create-namespace --region=region1 -s 96G 
[root]# ndctl create-namespace --region=region3 -s 64G 
[root]# ndctl create-namespace --region=region5 -s 32G 
[root]# ndctl list -N | grep -A1 namespace 
    "dev":"namespace1.0", 
    "mode":"fsdax", 
-- 
    "dev":"namespace3.0", 
    "mode":"fsdax", 
-- 
    "dev":"namespace5.0", 
    "mode":"fsdax", 

[root]# ndctl destroy-namespace -f all 
error destroying namespaces: No such device or address 
destroyed 3 namespaces 
[root@ban25uut130 ~]# echo $?                                       
250

**Comment by djbw** [comment] 2018-11-06 23:38
Duplicate of #73

**Comment by stellarhopper** [comment] 2018-12-05 20:55
Closing as duplicate

**Closed by stellarhopper** 2018-12-05 20:55 UTC
